name: Release

on:
  push:
    branches:
      - main
      - beta
      - '+([0-9])?(.{+([0-9]),x}).x'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test

    runs-on: ubuntu-latest

    # using trusted publishing. see https://docs.npmjs.com/trusted-publishers
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Generate token
        id: get_workflow_token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ secrets.NODE_CRON_RELEASE_APP_ID }}
          private-key: ${{ secrets.NODE_CRON_RELEASE_APP_PRIVATE_KEY }}

      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Use Node.js LTS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Audit npm signatures
        run: npm audit signatures

      - name: Build project
        run: npm run build

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          HUSKY: 0
